### ISSUE TITLE
Compiling with gstreamer 1.0

### ISSUE THREAD

**Issue by sbeyer** [copperspice/copperspice#54]
gstreamer 0.10 is not available any longer in current Debian sid, only gstreamer 1.0 is. This leads however (not really unexpected) to compile errors, e.g.,
```
src/3rdparty/phonon/gstreamer/artssink.cpp:77:58: error: ‘GstRingBufferSpec’ has not been declared
```

Are there plans to get copperspice to work with gstreamer 1.0?

More important to me: Can gstreamer be disabled using `./configure`? (I just want a minimal copperspice to run doxypress. I bet I don't need gstreamer support for that.)

**Comment by agserm** [comment]
Thank you for your issue report. We had this noted internally as a desired feature, and I have now filed both of these items in our public bug tracker:

http://redmine.copperspice.com/issues/29
http://redmine.copperspice.com/issues/30

**Comment by sbeyer** [comment]
Thank you.

**Comment by bretzel** [comment]
So CopperSipce is simply unusabe, unavail for common platforms like Archlinux; Because Of Gstreamer, GStream-Plugins; Audio ???? WOW!!!!!!!!!!!!!

**Comment by agserm** [comment]
bretzel,

We appreciate your willingness to look at CopperSpice. We currently support the Debian, Fedora, and Ubuntu Linux distributions. As you may or may not have seen from our other videos and documentation, we are certainly interested in knowing which platforms are relevant to our users. Your comment is the first to have mentioned Arch Linux and we are happy to investigate adding this platform to our CI set if you are interested.

In terms of GStreamer, we currently have a developer who is working on adding support for the 1.0 release and we are looking forward to this enhancement. If you have any other issues or concerns we look forward to working with you.  We would simply ask to keep the public GitHub discussion on a professional tone.

**Comment by bretzel** [comment]
Thank your for your reply. I must admit that gstreamer < 1.x is a problem
found in several Linux distributions. Archlinux and friends might be a
little bit too much ahead regarding gstreamer (1.12.x already!!!) ?? And
about the package named "Audio", sincerely who would name a package by a so
generic id :  "Audio" ? Is that another 90' qt' s legacy ? 😁

Therefore , I look forward to put my hands in a very promising Universal
gui framework. I have watched the CopperSpice  vidéo  tours and I say:
You're gods.

**Comment by agserm** [comment]
Yes, "Audio" is certainly not the best name for a library but someone in the Unix world named it and all these years later we are still stuck with it. We are glad to find out that GStreamer is a high priority for you and we look forward to community contributions, whether they are suggestions, pull requests, or any other sort of help. We are very glad to work with everyone who wants to contribute to the development of CopperSpice in any area of interest.

Thanks again for your input.

**Comment by mjsurette** [comment]
I would like to add OpenSUSE Tumbleweed as another distribution using gstreamer 1.0

I was able to download, build, and install nas, but that seems to be unmaintained, or should I say extremely stable.

I'll try the binaries for now, but would much prefer to be able to build it myself.

Mike

**Comment by marknovem** [comment]
I am using Kali Linux, i am downloading the Copperspice source but when i fetch the commnd: # "./configure" i got these build errors:  Gstreamer Gstreamer-Plugins Audio
Looking for a solution but still got no luck.. Hopefully these issue will be resolve soon... :D

**Comment by agserm** [comment]
marknovem, Kali linux is not a supported platform so we have not had any experience with the build process there. Can you give us a more complete error message? Depending on how Kali linux is configured, you may be able to avoid the dependency on gstreamer by passing `--disable-multimedia --disable-phonon` when configuring CopperSpice.

**Comment by marknovem** [comment]
Wow.. thanks for a quick reply.. Okay will try to build it again as soon as
possible when i got home. I will take note some more details during the
process and post it. Thanks for the hint.

**Comment by areriff** [comment]
This issue has been tracked a year ago. What is the current progress? 
Is copperspice.com down?

**Comment by marknovem** [comment]
Previously, under Kali Linux environment(Acer Travelmate P246 Series
Laptop), i execute:    root@mov:/mov/Downloads/copperspice-cs-1.4#
./configure
.....
.....
.....
checking for ALSA... no
checking for PULSEAUDIO... no
checking for PULSEAUDIO_DEVICE_MANAGER... no
checking for PULSEAUDIO_MAINLOOP_GLIB... no
checking for library containing IceOpenConnection... -lICE
checking for library containing AuOpenServer... no
checking for library containing glClear... -lGL
checking for library containing pthread_create... -lpthread
checking for library containing SmcOpenConnection... -lSM
checking for library containing XcursorImageCreate... -lXcursor
checking for library containing XShmCreateImage... -lXext
checking for library containing XFixesQueryVersion... -lXfixes
checking for library containing XGetExtensionVersion... -lXi
checking for library containing XineramaQueryExtension... -lXinerama
checking for library containing XRRSetScreenConfigAndRate... -lXrandr
checking for library containing XRenderCreateCursor... -lXrender
checking for library containing XCreateWindow... -lX11
------------------------------------------------------------
The following libraries are missing and must be installed to build
CopperSpice
Refer to the CS documentation for package names or consult your platform
package manager
Gstreamer Gstreamer-Plugins Audio
------------------------------------------------------------
CopperSpice configuration aborted
root@mov:/mov/Downloads/copperspice-cs-1.4#
************************************************************************************************************************************
Googling around and trying to install packages related to "Gstreamer
Gstreamer-Plugins Audio", still no luck..

I execute again with the suggested parameters, root@mov
:/mov/Downloads/copperspice-cs-1.4#./configure --disable-multimedia
--disable-phonon
....
....
....
checking for ALSA... no
checking for PULSEAUDIO... no
checking for PULSEAUDIO_DEVICE_MANAGER... no
checking for PULSEAUDIO_MAINLOOP_GLIB... no
checking for library containing IceOpenConnection... -lICE
checking for library containing AuOpenServer... no
checking for library containing glClear... -lGL
checking for library containing pthread_create... -lpthread
checking for library containing SmcOpenConnection... -lSM
checking for library containing XcursorImageCreate... -lXcursor
checking for library containing XShmCreateImage... -lXext
checking for library containing XFixesQueryVersion... -lXfixes
checking for library containing XGetExtensionVersion... -lXi
checking for library containing XineramaQueryExtension... -lXinerama
checking for library containing XRRSetScreenConfigAndRate... -lXrandr
checking for library containing XRenderCreateCursor... -lXrender
checking for library containing XCreateWindow... -lX11
------------------------------------------------------------
The following libraries are missing and must be installed to build
CopperSpice
Refer to the CS documentation for package names or consult your platform
package manager
Audio
------------------------------------------------------------

CopperSpice configuration aborted
root@mov:/mov/Downloads/copperspice-cs-1.4#
******************************************************************************
Still not working, what and where did i missed?

**Comment by areriff** [comment]
Currently CS only supports the deprecated gstreamer 0.1 and not the current 1.x correct?
Where can I find those. Arch repo no longer have them.

**Comment by agserm** [comment]
@marknovem, it looks like you are missing whichever development package provides the Audio library. This library is needed even with phonon and multimedia disabled. Since it appears that Kali is a derivative of Debian, this package is most likely called 'libaudio-dev'

**Comment by agserm** [comment]
@areriff, while I do not know much about Arch Linux, it does appear that gstreamer 0.1 is no longer available. In order to build CopperSpice on Arch Linux you would currently need to either build gstreamer 0.1 from source, or disable phonon and multimedia during the configuration process.

**Comment by gazzatav** [comment]
I just pulled from github and I'm trying to build Copperspice on Ubuntu 18.04.  I installed all the dependencies but configure fails with:

> The following libraries are missing and must be installed to build CopperSpice
> Refer to the CS documentation for package names or consult your platform package manager
> Gstreamer Gstreamer-Plugins

When I grep for Gstreamer Gstreamer-Plugins I find lines such as:

> configure.ac:PKG_CHECK_MODULES(GSTREAMER_AUDIO, gstreamer-audio-0.10, GSTREAMER_AUDIO="yes", missing="$missing Gstreamer-Plugins")

dpkg reveals that gstreamer-audio-0.10 is not installed and apt-cache search has no knowledge of any such package.

But Ubuntu 18.04 IS supported! I'd love to get started but the last post on this thread was a year ago.  Any news?

**Comment by agserm** [comment]
Thank you for your question. We still have this as an outstanding issue, and some developers are looking at porting CS to GStreamer 1.0. In the meantime, you can avoid the requirement for GStreamer entirely by building without Phonon and Multimedia by passing `--disable-multimedia --disable-phonon` to the configure script. You can see a list of the available configure options at https://www.copperspice.com/docs/cs_overview/build-options.html.

**Comment by gazzatav** [comment]
Thanks for your reply, much appreciated.  I had seen your comment earlier about Kali Linux but hadn't thought that this would apply to supported builds as well (that is not a criticism).  I have now successfully built the Copperspice libraries.

**Comment by agserm** [comment]
This issue will be resolved in the next release of CopperSpice which includes support for GStreamer 1.0.

**Comment by bgeller** [comment]
GStreamer 1.0 can successfully be used with CopperSpice 1.6.  We are preparing a release and prebuilt binary files will be available at the end of August.  The current Harfbuzz branch contains the code which will become CS 1.6.0.
