### ISSUE TITLE
Build issues with v1.6

### ISSUE THREAD

**Issue by hs-apotell** [copperspice/copperspice#117]
I had QCustomPlot working with v1.5 but having a hard time getting it to work with the newest v1.6 release. Lots of errors along the lines of the following -

csmeta.h(314,46): error C2338: Requested type name has not been registered. (compiling source file qcustomplot.cpp)

Has something changed in context to class/type registration in this release? 
Also, is the template registration for QSharedPointer missing in csmeta.h?

Appreciate some help on getting this to work again.

**Comment by janwilmans** [comment]
What would help us pickup this issue quickly is if you could provide a
minimal failing example?

Greetings,

Jan

**Comment by hs-apotell** [comment]
Project files attached.

Project is using VS2019 toolchain
Update CS path in Directory.Build.props on line 3
Update path to tool chain in Directory.Build.targets on line 5

[qcustomplot.zip](https://github.com/copperspice/copperspice/files/3747946/qcustomplot.zip)

**Comment by hs-apotell** [comment]
Could you please confirm whether or not you are able to reproduce the issue. Also, an ETA on a resolution would be good.

**Comment by bgeller** [comment]
> csmeta.h(314,46): error C2338: Requested type name has not been registered. 

Yes, we did change the meta system in CS 1.6.0 to report this as a compile time error. There was a potential problem with using the name of a class if it was not registered. This is now a static_assert(). 

Since you are using MSVC you should be able to get out of the error tab and find this error in the full compiler error log.  There will usually be more context and it should tell you which class is not registered. 

> Also, is the template registration for QSharedPointer missing in csmeta.h?

Yes, it does appear that we omitted this data type.  We are about to review this area of the code and enhance this section.  The template should really be registering itself rather than having a centralized list.  Thank you for pointing this out, we will escalate this change.

Barbara

**Comment by hs-apotell** [comment]
Is CS_REGISTER_CLASS and family the correct macros to use?

I am building QCustomPlot as a library and those macros don’t work because they have the dllimport/export keyword tagged to them. I have nearly 20 such projects that I build as library that are all dependent on CS. These libraries get linked in final executable. I don’t think having to explicitly register classes in the library using these macros would work, at least, not the way they are setup now. Are there any examples demonstrating this? Any test cases that were used to validate these breaking changes?

**Comment by hs-apotell** [comment]
I couldn't get the project to build using the existing CS_REGISTER_XXXX and the reported issues make logical sense. CS basically doesn't support static library build (not for CS itself but something that depends on CS, say a library or executable) and I am attempting to do exactly that. The only way I could get it to build was to make a copy of the meta macros in my project and remove the dllimport/export tag on them. I was able to use these modified macros to register the classes and get a working build.

One issue that still stands out is that not all classes needed the registration. Some of the classes report redefinition errors if I register them explicitly. I had to depend on the compiler to generate errors and tell me which classes needed explicit registration - that was quite an annoying process. Seems like there is an file order dependency issue when building. Is there a cleaner/logical way to figure out what classes need explicit registration?

Regardless, I hope what I had to do to get this working is a stop-gap solution and not the recommended solution. This issues does need to be resolved in CS itself or there should be documented ways of doing things to avoid the issue.

For my understanding, for classes subclassing CS internal classes (like say, QObject) and are outside of CS itself, say in a different library or executable, what decides that the class needs registration.

**Comment by bgeller** [comment]
> Is CS_REGISTER_CLASS and family the correct macros to use?

This is the macro which is used when you need a particular data type to be visible in the meta type system. You would need this when, for example, you want to user defined data type as a Signal or Slot parameter.  								

>I am building QCustomPlot as a library and those macros don’t work because they have the dllimport/export keyword tagged to them.

The key change we made was to add a static_assert() to ensure you can not query for the name of an unregistered type. This sometimes resulted in UB and other times returned a class name of empty. Both of which are very undesirable. 

Can you tell us what error message you receive when you call CS_REGISTER_CLASS? 

As a test it appears you have copied the implementation of the macro to your library. Please make sure you rename it and then you can safely remove the Q_CORE_EXPORT line. Does this solve your compile issue?

Your request is new and thus far has not been required. We are considering other solutions in CsCore to address your use case.  Please know this will be addressed. 

Barbara

**Comment by hs-apotell** [comment]
I am building a library that’s dependent on CS. I don’t see how this is “new” or an unusual use case. Isn’t supporting wildly used public libraries like QCustomPlot not a goal? Is such a thing part of your regular test suite for releases? Please elaborate. 

Yes, as you said, cloning the macro locally, renaming and stripping the Q_CORE_EXPORT fixes the problem. However, is that “the solution”?

I have shared a complete build-able project/solution among my previous messages. I recommend taking a moment to download and build that. It is simply a port of publicly available QCustomPlot library for CS.

**Comment by bgeller** [comment]
Please know, I never said you had an unusual use case.  Other developers use different approaches and this is your approach. So lets work together as a team. 

Our aim is to work out your use case, which we feel is of value and worthwhile.  It will however require the CopperSpice team to ask questions and determine the best way to solve things without causing regressions. 

I never said that cloning the macro and making a local change was the final solution. What I asked, was does this provide you with a solution.  If so, then you have a stop gap which is one of the things you asked for.  Now that we know it does help,  we can determine the best way to proceed.

We have your information and our next step is to work with our team members and consider options, which we will do regardless of how you decide to proceed.  

I want to be clear, we care deeply about user experiences and hope you and others can work with us to improve CopperSpice.

Barbara

**Comment by hs-apotell** [comment]
I wasn't trying to be confrontational by any means. Things don't spell out the same when one is on the tiny phone screen trying hard not to lose other person's attention. That surely is not my intention. Losing your confidence is not in my best interest :)

> Other developers use different approaches

What other approaches are we talking about? I have nearly 20 such small libraries some with even just one class implementation. Converting them all to DLLs wouldn't scale well for us and dynamic libraries come with their own nightmarish headaches (custom memory management being the most important to us).

More on the test case I provided - The project is not using a library approach. It's building all as a single exe project and still running into this problem. And since now I am back on my computer, here are the error messages reported when using ```CS_DECLARE_CLASS/CS_REGISTER_CLASS``` macros in place of the cloned ones.

```
error C2491: 'cs_typeName_internal<QCPRange,void>::typeName': definition of dllimport function not allowed
error C2491: 'cs_typeName_internal<QCPDataSelection,void>::typeName': definition of dllimport function not allowed
```
And the same are repeated for every use of the macro.

**Comment by bgeller** [comment]
Thanks for you reply, it means a lot to us and the full CopperSpice team.  Glad we can work together and we will keep you in the loop. 

We are actively looking at a few things and talking about how to solve this for the 15+ platforms / operating systems we currently support. Funny how one solution for Arch breaks Debian and the next one impacts MSVC.  We want solutions that work everywhere and that sometimes takes a bit more effort and time. 

Please keep going and let us know what else we can improve. 

Barbara

**Comment by agserm** [comment]
We are currently working on a new design for QVariant and looking at how to implement auto registration for the meta type system. Our direction is to remove the requirement for some of these macros. We should have something in the next month.

**Comment by bgeller** [comment]
Have you moved to CS 1.7 and tried your code with our new QVariant system?

**Comment by agserm** [comment]
Closing since there is no pending issue. Reopen if you have more questions.
