### ISSUE TITLE
Cannot compile on macOS 10.12

### ISSUE THREAD

**Issue by rwols** [copperspice/copperspice#56]
It looks like there are some references to QT:
```
[15/248] Building CXX object src/phonon/CMakeFiles/phonon_qt7.dir/__/3rdparty/phonon/qt7/backendinfo.mm.o
FAILED: src/phonon/CMakeFiles/phonon_qt7.dir/__/3rdparty/phonon/qt7/backendinfo.mm.o 
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++    @src/phonon/CMakeFiles/phonon_qt7.dir/__/3rdparty/phonon/qt7/backendinfo.mm.o.rsp -MD -MT src/phonon/CMakeFiles/phonon_qt7.dir/__/3rdparty/phonon/qt7/backendinfo.mm.o -MF src/phonon/CMakeFiles/phonon_qt7.dir/__/3rdparty/phonon/qt7/backendinfo.mm.o.d -o src/phonon/CMakeFiles/phonon_qt7.dir/__/3rdparty/phonon/qt7/backendinfo.mm.o -c ../src/3rdparty/phonon/qt7/backendinfo.mm
../src/3rdparty/phonon/qt7/backendinfo.mm:23:9: fatal error: 'QTKit/QTMovie.h' file not found
#import <QTKit/QTMovie.h>
        ^
1 error generated.
[16/248] Building CXX object src/phonon/CMakeFiles/phonon_qt7.dir/__/3rdparty/phonon/qt7/quicktimevideoplayer.mm.o
FAILED: src/phonon/CMakeFiles/phonon_qt7.dir/__/3rdparty/phonon/qt7/quicktimevideoplayer.mm.o 
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++    @src/phonon/CMakeFiles/phonon_qt7.dir/__/3rdparty/phonon/qt7/quicktimevideoplayer.mm.o.rsp -MD -MT src/phonon/CMakeFiles/phonon_qt7.dir/__/3rdparty/phonon/qt7/quicktimevideoplayer.mm.o -MF src/phonon/CMakeFiles/phonon_qt7.dir/__/3rdparty/phonon/qt7/quicktimevideoplayer.mm.o.d -o src/phonon/CMakeFiles/phonon_qt7.dir/__/3rdparty/phonon/qt7/quicktimevideoplayer.mm.o -c ../src/3rdparty/phonon/qt7/quicktimevideoplayer.mm
In file included from ../src/3rdparty/phonon/qt7/quicktimevideoplayer.mm:23:
../src/3rdparty/phonon/qt7/quicktimevideoplayer.h:28:9: fatal error: 'QTKit/QTDataReference.h' file not found
#import <QTKit/QTDataReference.h>
        ^
```

[Here](https://github.com/copperspice/copperspice/blob/cs-1.4/src/3rdparty/phonon/qt7/backendinfo.mm#L23), and [here](https://github.com/copperspice/copperspice/blob/cs-1.4/src/3rdparty/phonon/qt7/quicktimevideoplayer.h#L28-L29).

Is this supposed to happen? Do I still need the QT library?

**Comment by agserm** [comment]
Hi Raoul,

No, this is certainly not supposed to happen and you should not need the Qt library in any way to build CopperSpice. Confusingly, QTKit/QTMovie.h is not provided by Qt or CopperSpice, but rather the Apple QuickTime framework. It sounds as if the QuickTime framework is not being properly added to the Objective-C compile flags for some reason. Would you please re-run ninja with a `-v` for the full compile command line? I will try a few things and see if I can reproduce on our end as well.

Thanks,
Ansel

**Comment by rwols** [comment]
Hi Ansel,

Thanks for the reply. Here is ninja in verbose mode:
```
rwols@Air-van-Raoul ~> cd ~/dev/copperspice/
rwols@Air-van-Raoul ~/d/copperspice> cd build
rwols@Air-van-Raoul ~/d/c/build> ninja -v
[1/230] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++    @src/phonon/CMakeFiles/phonon_qt7.dir/__/3rdparty/phonon/qt7/backendinfo.mm.o.rsp -MD -MT src/phonon/CMakeFiles/phonon_qt7.dir/__/3rdparty/phonon/qt7/backendinfo.mm.o -MF src/phonon/CMakeFiles/phonon_qt7.dir/__/3rdparty/phonon/qt7/backendinfo.mm.o.d -o src/phonon/CMakeFiles/phonon_qt7.dir/__/3rdparty/phonon/qt7/backendinfo.mm.o -c ../src/3rdparty/phonon/qt7/backendinfo.mm
FAILED: src/phonon/CMakeFiles/phonon_qt7.dir/__/3rdparty/phonon/qt7/backendinfo.mm.o 
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++    @src/phonon/CMakeFiles/phonon_qt7.dir/__/3rdparty/phonon/qt7/backendinfo.mm.o.rsp -MD -MT src/phonon/CMakeFiles/phonon_qt7.dir/__/3rdparty/phonon/qt7/backendinfo.mm.o -MF src/phonon/CMakeFiles/phonon_qt7.dir/__/3rdparty/phonon/qt7/backendinfo.mm.o.d -o src/phonon/CMakeFiles/phonon_qt7.dir/__/3rdparty/phonon/qt7/backendinfo.mm.o -c ../src/3rdparty/phonon/qt7/backendinfo.mm
../src/3rdparty/phonon/qt7/backendinfo.mm:23:9: fatal error: 'QTKit/QTMovie.h' file not found
#import <QTKit/QTMovie.h>
        ^
1 error generated.
[2/230] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++    @src/phonon/CMakeFiles/phonon_qt7.dir/__/3rdparty/phonon/qt7/mediaobjectaudionode.mm.o.rsp -MD -MT src/phonon/CMakeFiles/phonon_qt7.dir/__/3rdparty/phonon/qt7/mediaobjectaudionode.mm.o -MF src/phonon/CMakeFiles/phonon_qt7.dir/__/3rdparty/phonon/qt7/mediaobjectaudionode.mm.o.d -o src/phonon/CMakeFiles/phonon_qt7.dir/__/3rdparty/phonon/qt7/mediaobjectaudionode.mm.o -c ../src/3rdparty/phonon/qt7/mediaobjectaudionode.mm
FAILED: src/phonon/CMakeFiles/phonon_qt7.dir/__/3rdparty/phonon/qt7/mediaobjectaudionode.mm.o 
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++    @src/phonon/CMakeFiles/phonon_qt7.dir/__/3rdparty/phonon/qt7/mediaobjectaudionode.mm.o.rsp -MD -MT src/phonon/CMakeFiles/phonon_qt7.dir/__/3rdparty/phonon/qt7/mediaobjectaudionode.mm.o -MF src/phonon/CMakeFiles/phonon_qt7.dir/__/3rdparty/phonon/qt7/mediaobjectaudionode.mm.o.d -o src/phonon/CMakeFiles/phonon_qt7.dir/__/3rdparty/phonon/qt7/mediaobjectaudionode.mm.o -c ../src/3rdparty/phonon/qt7/mediaobjectaudionode.mm
../src/3rdparty/phonon/qt7/mediaobjectaudionode.mm:27:9: fatal error: 'QTKit/QTMovie.h' file not found
#import <QTKit/QTMovie.h>
        ^
1 error generated.
[3/230] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++    @src/phonon/CMakeFiles/phonon_qt7.dir/__/3rdparty/phonon/qt7/quicktimevideoplayer.mm.o.rsp -MD -MT src/phonon/CMakeFiles/phonon_qt7.dir/__/3rdparty/phonon/qt7/quicktimevideoplayer.mm.o -MF src/phonon/CMakeFiles/phonon_qt7.dir/__/3rdparty/phonon/qt7/quicktimevideoplayer.mm.o.d -o src/phonon/CMakeFiles/phonon_qt7.dir/__/3rdparty/phonon/qt7/quicktimevideoplayer.mm.o -c ../src/3rdparty/phonon/qt7/quicktimevideoplayer.mm
FAILED: src/phonon/CMakeFiles/phonon_qt7.dir/__/3rdparty/phonon/qt7/quicktimevideoplayer.mm.o 
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++    @src/phonon/CMakeFiles/phonon_qt7.dir/__/3rdparty/phonon/qt7/quicktimevideoplayer.mm.o.rsp -MD -MT src/phonon/CMakeFiles/phonon_qt7.dir/__/3rdparty/phonon/qt7/quicktimevideoplayer.mm.o -MF src/phonon/CMakeFiles/phonon_qt7.dir/__/3rdparty/phonon/qt7/quicktimevideoplayer.mm.o.d -o src/phonon/CMakeFiles/phonon_qt7.dir/__/3rdparty/phonon/qt7/quicktimevideoplayer.mm.o -c ../src/3rdparty/phonon/qt7/quicktimevideoplayer.mm
In file included from ../src/3rdparty/phonon/qt7/quicktimevideoplayer.mm:23:
../src/3rdparty/phonon/qt7/quicktimevideoplayer.h:28:9: fatal error: 'QTKit/QTDataReference.h' file not found
#import <QTKit/QTDataReference.h>
        ^
1 error generated.
[4/230] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++    @src/phonon/CMakeFiles/phonon_qt7.dir/__/3rdparty/phonon/qt7/medianode.mm.o.rsp -MD -MT src/phonon/CMakeFiles/phonon_qt7.dir/__/3rdparty/phonon/qt7/medianode.mm.o -MF src/phonon/CMakeFiles/phonon_qt7.dir/__/3rdparty/phonon/qt7/medianode.mm.o.d -o src/phonon/CMakeFiles/phonon_qt7.dir/__/3rdparty/phonon/qt7/medianode.mm.o -c ../src/3rdparty/phonon/qt7/medianode.mm
FAILED: src/phonon/CMakeFiles/phonon_qt7.dir/__/3rdparty/phonon/qt7/medianode.mm.o 
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++    @src/phonon/CMakeFiles/phonon_qt7.dir/__/3rdparty/phonon/qt7/medianode.mm.o.rsp -MD -MT src/phonon/CMakeFiles/phonon_qt7.dir/__/3rdparty/phonon/qt7/medianode.mm.o -MF src/phonon/CMakeFiles/phonon_qt7.dir/__/3rdparty/phonon/qt7/medianode.mm.o.d -o src/phonon/CMakeFiles/phonon_qt7.dir/__/3rdparty/phonon/qt7/medianode.mm.o -c ../src/3rdparty/phonon/qt7/medianode.mm
In file included from ../src/3rdparty/phonon/qt7/medianode.mm:34:
../src/3rdparty/phonon/qt7/quicktimevideoplayer.h:28:9: fatal error: 'QTKit/QTDataReference.h' file not found
#import <QTKit/QTDataReference.h>
        ^
1 error generated.
[5/230] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++    @src/phonon/CMakeFiles/phonon_qt7.dir/__/3rdparty/phonon/qt7/mediaobject.mm.o.rsp -MD -MT src/phonon/CMakeFiles/phonon_qt7.dir/__/3rdparty/phonon/qt7/mediaobject.mm.o -MF src/phonon/CMakeFiles/phonon_qt7.dir/__/3rdparty/phonon/qt7/mediaobject.mm.o.d -o src/phonon/CMakeFiles/phonon_qt7.dir/__/3rdparty/phonon/qt7/mediaobject.mm.o -c ../src/3rdparty/phonon/qt7/mediaobject.mm
FAILED: src/phonon/CMakeFiles/phonon_qt7.dir/__/3rdparty/phonon/qt7/mediaobject.mm.o 
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++    @src/phonon/CMakeFiles/phonon_qt7.dir/__/3rdparty/phonon/qt7/mediaobject.mm.o.rsp -MD -MT src/phonon/CMakeFiles/phonon_qt7.dir/__/3rdparty/phonon/qt7/mediaobject.mm.o -MF src/phonon/CMakeFiles/phonon_qt7.dir/__/3rdparty/phonon/qt7/mediaobject.mm.o.d -o src/phonon/CMakeFiles/phonon_qt7.dir/__/3rdparty/phonon/qt7/mediaobject.mm.o -c ../src/3rdparty/phonon/qt7/mediaobject.mm
In file included from ../src/3rdparty/phonon/qt7/mediaobject.mm:33:
../src/3rdparty/phonon/qt7/quicktimevideoplayer.h:28:9: fatal error: 'QTKit/QTDataReference.h' file not found
#import <QTKit/QTDataReference.h>
        ^
1 error generated.
[6/230] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++    @src/phonon/CMakeFiles/phonon_qt7.dir/__/3rdparty/phonon/qt7/audiomixer.mm.o.rsp -MD -MT src/phonon/CMakeFiles/phonon_qt7.dir/__/3rdparty/phonon/qt7/audiomixer.mm.o -MF src/phonon/CMakeFiles/phonon_qt7.dir/__/3rdparty/phonon/qt7/audiomixer.mm.o.d -o src/phonon/CMakeFiles/phonon_qt7.dir/__/3rdparty/phonon/qt7/audiomixer.mm.o -c ../src/3rdparty/phonon/qt7/audiomixer.mm
ninja: build stopped: subcommand failed.
```

**Comment by rwols** [comment]
> Confusingly, QTKit/QTMovie.h is not provided by Qt or CopperSpice, but rather the Apple QuickTime framework.

Whoops, yeah, this makes total sense.

I dug around a bit in the CMakeLists.txt file, and it looks like `-framework QTKit` is added for the phonos target.

It seems Apple removed this framework. [Tangentially related issue for OpenCV](https://github.com/opencv/opencv/issues/6913). It looks like you'll have to [move to AVFoundation](https://github.com/opencv/opencv/pull/6802).

I disabled CsMultimedia and CsWebKit (because it's huge), and it all compiles now.

**Comment by agserm** [comment]
We have added the ability in the Autotools build to turn off multimedia as well as other libraries, as now documented here: http://www.copperspice.com/docs/cs_overview/build-options.html

We just added Sierra to our CI system and we will be investigating our options for using AVFoundation to restore the ability to build CopperSpice with multimedia functionality.
