### ISSUE TITLE
Unable to compile on clang 15.0.2

### ISSUE THREAD

**Issue by 3oheicrw** [copperspice/copperspice#241]
This is MSYS2's `mingw-w64-clang-x86_64-toolchain`.

```
$ clang -v
clang version 15.0.2
Target: x86_64-w64-windows-gnu
Thread model: posix
InstalledDir: C:/msys64/clang64/bin
```

The error message:

```
FAILED: src/core/CMakeFiles/CsCore.dir/io/qfilesystemengine_win.cpp.obj
C:\msys64\clang64\bin\c++.exe @src\core\CMakeFiles\CsCore.dir\io\qfilesystemengine_win.cpp.obj.rsp -MD -MT src/core/CMakeFiles/CsCore.dir/io/qfilesystemengine_win.cpp.obj -MF src\core\CMakeFiles\CsCore.dir\io\qfilesystemengine_win.cpp.obj.d -o src/core/CMakeFiles/CsCore.dir/io/qfilesystemengine_win.cpp.obj -c C:/msys64/home/Administrator/mulle-clang/clang64/copperspice/src/core/io/qfilesystemengine_win.cpp
C:/msys64/home/Administrator/mulle-clang/clang64/copperspice/src/core/io/qfilesystemengine_win.cpp:649:7: error: unknown type name 'FILE_ID_INFO'
      FILE_ID_INFO infoEx;
      ^
C:/msys64/home/Administrator/mulle-clang/clang64/copperspice/src/core/io/qfilesystemengine_win.cpp:651:78: error: use of undeclared identifier 'FILE_ID_INFO'; did you mean 'SIID_INFO'?
      if (getFileInformationByHandleEx(handle, Q_FileIdInfo, &infoEx, sizeof(FILE_ID_INFO))) {
                                                                             ^~~~~~~~~~~~
                                                                             SIID_INFO
C:/msys64/clang64/include/shellapi.h:695:5: note: 'SIID_INFO' declared here
    SIID_INFO = 79,
    ^
2 errors generated.
```

**Comment by 3oheicrw** [comment]
I found a very similar Qt bug: https://bugreports.qt.io/browse/QTBUG-94031

**Comment by bgeller** [comment]
We have not added clang 15 to our CI as of yet.  Is it possible for you to try building on a non-windows platform?  It would be good to know if this is an issue with newer versions of clang or using clang on Windows.

**Comment by 3oheicrw** [comment]
> We have not added clang 15 to our CI as of yet. Is it possible for you to try building on a non-windows platform? It would be good to know if this is an issue with newer versions of clang or using clang on Windows.

It seems to be a bug only happens with MinGW platform. See the bug I linked (and you removed).
