### ISSUE TITLE
Compile error while building

### ISSUE THREAD

**Issue by wpbest** [copperspice/copperspice#12]
While trying to compile on a Mac with OS X 10.11.1, latest home-brew and autotools (autoconf-2.69, automake-1.15)  installed I get the following error:

In file included from src/core/animation/qabstractanimation.cpp:28:
In file included from include/QtCore/qdebug.h:30:
include/QtCore/qhash.h:111:57: error: redefinition of default argument
template <class T> inline uint qHash(const T *key, uint seed = 0)
                                                        ^      ~
include/QtCore/qsharedpointer_impl.h:75:31: note: previous definition is here
uint qHash(const T *key, uint seed = 0);
                              ^      ~
1 error generated.
make[2]: *** [src/core/animation/lib_libCsCore1_la-qabstractanimation.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

**Comment by bgeller** [comment]
Sorry for the late reply, we were unaware of the comments on GitHub. Our intention was to have all comments posted to our forum. 

We currently build on 10.10 and this we know it builds on that system  Our OS X system currently be upgraded and we are planning on testing 10.11 very soon.  

Sorry for the inconvenience.  We have noted your issue. 

Barbara

**Comment by ahmedcharles** [comment]
I believe this was fixed, can you try again, @wpbest

**Comment by bgeller** [comment]
Closing this issue. If you find any problems please let us know.
